// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using noughtsandcrosses.api.Repositories;

namespace noughtsandcrosses.api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181011193400_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("noughtsandcrosses.api.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardDimension");

                    b.Property<bool>("IsTerminal");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("noughtsandcrosses.api.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsGameOver");

                    b.Property<bool>("IsGameWon");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("noughtsandcrosses.api.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerLevel");

                    b.Property<string>("PlayerName");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("noughtsandcrosses.Server.Repositories.Models.SignUp", b =>
                {
                    b.Property<int>("SignUpId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Email");

                    b.Property<string>("Nickname");

                    b.Property<string>("Password");

                    b.HasKey("SignUpId");

                    b.ToTable("SignUps");
                });
#pragma warning restore 612, 618
        }
    }
}
