// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using noughtsandcrosses.api.Repositories;

namespace noughtsandcrosses.api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20181029163332_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("noughtsandcrosses.api.Repositories.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardDimension");

                    b.Property<bool>("IsTerminal");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("noughtsandcrosses.api.Repositories.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsGameOver");

                    b.Property<bool>("IsGameWon");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("noughtsandcrosses.api.Repositories.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerLevel");

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
