// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoughtsAndCrosses.Src.Repositories;

namespace NoughtsAndCrossesApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("NoughtsAndCrosses.Server.Src.Repositories.Models.Board", b =>
                {
                    b.Property<int>("BoardId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardDimension");

                    b.Property<string>("BoardState");

                    b.Property<bool>("IsTerminal");

                    b.HasKey("BoardId");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("NoughtsAndCrosses.Server.Src.Repositories.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BoardDimension");

                    b.Property<int>("GameLevel");

                    b.Property<bool>("IsGameOver");

                    b.Property<bool>("IsGameWon");

                    b.Property<int>("TurnChoice");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("NoughtsAndCrosses.Server.Src.Repositories.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PlayerLevel");

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
